name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 115455868438.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t lambda-nodejs-repo .
          docker tag lambda-nodejs-repo:latest 115455868438.dkr.ecr.us-east-1.amazonaws.com/lambda-nodejs-repo:latest
          docker push 115455868438.dkr.ecr.us-east-1.amazonaws.com/lambda-nodejs-repo:latest

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
